TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += icefrdge.db
DB += loop.db
DB += valve.db
DB += proportional_valve.db
DB += solenoid_valve.db
DATA += icefrdge.proto


#=======================================
include $(TOP)/configure/RULES
