TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += icefrdge.db
DB += loop.db
DATA += icefrdge.proto


#=======================================
include $(TOP)/configure/RULES
